import Head from 'next/head'
import Navbar from '../components/Navbar/Navbar'
import HeroSection from '../components/HeroSection/HeroSection'
import Footer from '../components/Footer/Footer';
import CTASection from '../components/CTASection/CTASection';
import FeatureSection from '../components/FeatureSection/FeatureSection';
import WorkShow from '../components/WorkShowSection/WorkShow';
import TestimonialSection from '../components/TestimonialSection/TestimonialSection';
import VideoSection from '../components/VideoSection/VideoSection';
import AttributeSection from '../components/AttributeSection/AttributeSection';
import BackToTop from '../components/UI/BackToTop/BackToTop'

export default function Home() {
  return (
    <>
      <Head>
        <title>Queue One</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Navbar />
      <HeroSection />
      <BackToTop />
      <VideoSection />
      <FeatureSection />
      <WorkShow />
      <AttributeSection />
      <TestimonialSection />
      <CTASection />
      <Footer />
      
    </>
  )
}
